FROM alpine:3.22

RUN apk upgrade --no-cache \
    && apk add --no-cache ffmpeg tini \
    && addgroup -S streamer \
    && adduser -S -G streamer streamer

COPY --chown=streamer:streamer loop.sh /usr/local/bin/broadcast-loop
RUN chmod 0555 /usr/local/bin/broadcast-loop

USER streamer

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/broadcast-loop"]
